### ISSUE TITLE
Internal server error for eidaws-wfcatalog|fdsnws-dataselect

### ISSUE THREAD

**Issue by damb** [EIDA/eidaws-federator-deployment#6]
Requests which do not specify any *SNCL* related query filter parameter seem to return an Internal server error (i.e. HTTP status code **500**). E.g.

- `fdsnws-dataselect`:

```
$ curl -v -o - "http://eida-federator.ethz.ch/fdsnws/dataselect/1/query?starttime=2020-01-04&endtime=2020-01-05"
*   Trying 129.132.148.115:80...
* Connected to eida-federator.ethz.ch (129.132.148.115) port 80 (#0)
> GET /fdsnws/dataselect/1/query?starttime=2020-01-04&endtime=2020-01-05 HTTP/1.1
> Host: eida-federator.ethz.ch
> User-Agent: curl/7.78.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.18.0 (Ubuntu)
< Date: Wed, 08 Sep 2021 12:19:47 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 554
< Connection: keep-alive
< 

Error 500: Internal server error

Error while routing: 500, message='INTERNAL SERVER ERROR', url=URL('http://eidaws-stationlite:8089/eidaws/routing/1/query?service=dataselect&format=post&access=open&network=*&station=*&location=*&channel=*&starttime=2020-01-04T00:00:00&endtime=2020-01-05T00:00:00')

Usage details are available from http://www.fdsn.org/webservices/

Request:
http://eida-federator.ethz.ch/fedws/dataselect/miniseed/1/query?starttime=2020-01-04&endtime=2020-01-05

Request Submitted:
2021-09-08T12:19:44.899611

Service version:
0.12.1
* Connection #0 to host eida-federator.ethz.ch left intact
```

- `eidaws-wfcatalog`:

```
$ curl -v -o - "http://eida-federator.ethz.ch/eidaws/wfcatalog/1/query?starttime=1970-01-01&endtime=2020-01-10"
*   Trying 129.132.148.115:80...
* Connected to eida-federator.ethz.ch (129.132.148.115) port 80 (#0)
> GET /eidaws/wfcatalog/1/query?starttime=1970-01-01&endtime=2020-01-10 HTTP/1.1
> Host: eida-federator.ethz.ch
> User-Agent: curl/7.78.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.18.0 (Ubuntu)
< Date: Wed, 08 Sep 2021 12:23:49 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 547
< Connection: keep-alive
< 

Error 500: Internal server error

Error while routing: 500, message='INTERNAL SERVER ERROR', url=URL('http://eidaws-stationlite:8089/eidaws/routing/1/query?service=wfcatalog&format=post&access=any&network=*&station=*&location=*&channel=*&starttime=1970-01-01T00:00:00&endtime=2020-01-10T00:00:00')

Usage details are available from http://www.fdsn.org/webservices/

Request:
http://eida-federator.ethz.ch/fedws/wfcatalog/json/1/query?starttime=1970-01-01&endtime=2020-01-10

Request Submitted:
2021-09-08T12:23:46.010060

Service version:
0.12.1
* Connection #0 to host eida-federator.ethz.ch left intact
```

**Comment by damb** [comment]
Here the related logs:

```
eidaws-federator       | Sep  8 12:28:39 6f6e58b7ca0b <EIDA> 2021-09-08T12:28:39+0000 INFO eidaws.federator.middleware 91 misc.py:228 - [969f3446-1d64-4619-9ee5-f0f725c0858f]  2021-09-08T12:28:39.892635 "GET /fedws/wfcatalog/json/1/query?starttime=2020-01-04&endtime=2020-01-10 HTTP/1.1' '-' 'curl/7.78.0'
eidaws-stationlite-psql | 2021-09-08 12:28:43.811 UTC [246] ERROR:  could not resize shared memory segment "/PostgreSQL.541514444" to 16777216 bytes: No space left on device
eidaws-stationlite-psql | 2021-09-08 12:28:43.811 UTC [246] STATEMENT:  SELECT DISTINCT channelepoch.code AS channelepoch_code, channelepoch.locationcode AS channelepoch_locationcode, station.code AS station_code, network.code AS network_code, epoch.starttime AS epoch_starttime, epoch.endtime AS epoch_endtime, routing.starttime AS routing_starttime, routing.endtime AS routing_endtime, endpoint.url AS endpoint_url 
eidaws-stationlite-psql | 	FROM channelepoch JOIN epoch ON channelepoch.epoch_ref = epoch.id JOIN epochtype ON epoch.epochtype_ref = epochtype.id JOIN routing ON routing.epoch_ref = epoch.id JOIN network ON channelepoch.network_ref = network.id JOIN station ON channelepoch.station_ref = station.id JOIN stationepoch ON stationepoch.station_ref = station.id JOIN endpoint ON routing.endpoint_ref = endpoint.id JOIN service ON endpoint.service_ref = service.id 
eidaws-stationlite-psql | 	WHERE network.code LIKE '%' ESCAPE '/' AND station.code LIKE '%' ESCAPE '/' AND channelepoch.code LIKE '%' ESCAPE '/' AND channelepoch.locationcode LIKE '%' ESCAPE '/' AND service.name = 'wfcatalog' AND epochtype.type = 'CHANNEL' AND stationepoch.latitude >=  -90.0 AND stationepoch.latitude <= 90.0 AND stationepoch.longitude >=  -180.0 AND stationepoch.longitude <= 180.0 AND (epoch.endtime > '2020-01-04T00:00:00'::timestamp OR epoch.endtime IS NULL) AND epoch.starttime < '2020-01-10T00:00:00'::timestamp
eidaws-stationlite-psql | 2021-09-08 12:28:43.811 UTC [35] ERROR:  could not resize shared memory segment "/PostgreSQL.541514444" to 16777216 bytes: No space left on device
eidaws-stationlite-psql | 2021-09-08 12:28:43.811 UTC [35] CONTEXT:  parallel worker
eidaws-stationlite-psql | 2021-09-08 12:28:43.811 UTC [35] STATEMENT:  SELECT DISTINCT channelepoch.code AS channelepoch_code, channelepoch.locationcode AS channelepoch_locationcode, station.code AS station_code, network.code AS network_code, epoch.starttime AS epoch_starttime, epoch.endtime AS epoch_endtime, routing.starttime AS routing_starttime, routing.endtime AS routing_endtime, endpoint.url AS endpoint_url 
eidaws-stationlite-psql | 	FROM channelepoch JOIN epoch ON channelepoch.epoch_ref = epoch.id JOIN epochtype ON epoch.epochtype_ref = epochtype.id JOIN routing ON routing.epoch_ref = epoch.id JOIN network ON channelepoch.network_ref = network.id JOIN station ON channelepoch.station_ref = station.id JOIN stationepoch ON stationepoch.station_ref = station.id JOIN endpoint ON routing.endpoint_ref = endpoint.id JOIN service ON endpoint.service_ref = service.id 
eidaws-stationlite-psql | 	WHERE network.code LIKE '%' ESCAPE '/' AND station.code LIKE '%' ESCAPE '/' AND channelepoch.code LIKE '%' ESCAPE '/' AND channelepoch.locationcode LIKE '%' ESCAPE '/' AND service.name = 'wfcatalog' AND epochtype.type = 'CHANNEL' AND stationepoch.latitude >=  -90.0 AND stationepoch.latitude <= 90.0 AND stationepoch.longitude >=  -180.0 AND stationepoch.longitude <= 180.0 AND (epoch.endtime > '2020-01-04T00:00:00'::timestamp OR epoch.endtime IS NULL) AND epoch.starttime < '2020-01-10T00:00:00'::timestamp
eidaws-stationlite-psql | 2021-09-08 12:28:43.812 UTC [245] FATAL:  terminating connection due to administrator command
eidaws-stationlite-psql | 2021-09-08 12:28:43.812 UTC [245] STATEMENT:  SELECT DISTINCT channelepoch.code AS channelepoch_code, channelepoch.locationcode AS channelepoch_locationcode, station.code AS station_code, network.code AS network_code, epoch.starttime AS epoch_starttime, epoch.endtime AS epoch_endtime, routing.starttime AS routing_starttime, routing.endtime AS routing_endtime, endpoint.url AS endpoint_url 
eidaws-stationlite-psql | 	FROM channelepoch JOIN epoch ON channelepoch.epoch_ref = epoch.id JOIN epochtype ON epoch.epochtype_ref = epochtype.id JOIN routing ON routing.epoch_ref = epoch.id JOIN network ON channelepoch.network_ref = network.id JOIN station ON channelepoch.station_ref = station.id JOIN stationepoch ON stationepoch.station_ref = station.id JOIN endpoint ON routing.endpoint_ref = endpoint.id JOIN service ON endpoint.service_ref = service.id 
eidaws-stationlite-psql | 	WHERE network.code LIKE '%' ESCAPE '/' AND station.code LIKE '%' ESCAPE '/' AND channelepoch.code LIKE '%' ESCAPE '/' AND channelepoch.locationcode LIKE '%' ESCAPE '/' AND service.name = 'wfcatalog' AND epochtype.type = 'CHANNEL' AND stationepoch.latitude >=  -90.0 AND stationepoch.latitude <= 90.0 AND stationepoch.longitude >=  -180.0 AND stationepoch.longitude <= 180.0 AND (epoch.endtime > '2020-01-04T00:00:00'::timestamp OR epoch.endtime IS NULL) AND epoch.starttime < '2020-01-10T00:00:00'::timestamp
eidaws-stationlite-psql | 2021-09-08 12:28:43.824 UTC [1] LOG:  background worker "parallel worker" (PID 246) exited with exit code 1
eidaws-stationlite-psql | 2021-09-08 12:28:43.995 UTC [1] LOG:  background worker "parallel worker" (PID 245) exited with exit code 1
eidaws-stationlite     | Sep  8 12:28:44 1fe0d15a4e26 <EIDA> 2021-09-08T12:28:44+0000 CRITICAL eidaws.stationlite 49 __init__.py:71 - Local Exception: <class 'sqlalchemy.exc.OperationalError'>
eidaws-stationlite     | Sep  8 12:28:44 1fe0d15a4e26 <EIDA> 2021-09-08T12:28:44+0000 CRITICAL eidaws.stationlite 49 __init__.py:72 - Traceback information: ['Traceback (most recent call last):\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context\n    self.dialect.do_execute(\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute\n    cursor.execute(statement, parameters)\n', 'psycopg2.errors.DiskFull: could not resize shared memory segment "/PostgreSQL.541514444" to 16777216 bytes: No space left on device\nCONTEXT:  parallel worker\n\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request\n    rv = self.dispatch_request()\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/flask/views.py", line 83, in view\n    return self.dispatch_request(*args, **kwargs)\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/flask/views.py", line 157, in dispatch_request\n    return meth(*args, **kwargs)\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/webargs/core.py", line 459, in wrapper\n    return func(*new_args, **kwargs)\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/webargs/core.py", line 455, in wrapper\n    return func(*args, **kwargs)\n', '  File "/usr/local/src/eidaws/eidaws.stationlite/eidaws/stationlite/server/strict.py", line 35, in wrapper\n    return func(*args, **kwargs)\n', '  File "/usr/local/src/eidaws/eidaws.stationlite/eidaws/stationlite/server/routing/view.py", line 97, in get\n    return self._make_response(args, stream_epochs)\n', '  File "/usr/local/src/eidaws/eidaws.stationlite/eidaws/stationlite/server/routing/view.py", line 115, in _make_response\n    payload = self._process_request(\n', '  File "/usr/local/src/eidaws/eidaws.stationlite/eidaws/stationlite/server/routing/view.py", line 159, in _process_request\n    _routes = query_routes(\n', '  File "/usr/local/src/eidaws/eidaws.stationlite/eidaws/stationlite/core/query.py", line 167, in query_routes\n    for row in query.all():\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all\n    return self._iter().all()\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter\n    result = self.session.execute(\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1689, in execute\n    result = conn._execute_20(statement, params or {}, execution_options)\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20\n    return meth(self, args_10style, kwargs_10style, execution_options)\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection\n    return connection._execute_clauseelement(\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement\n    ret = self._execute_context(\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context\n    self._handle_dbapi_exception(\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception\n    util.raise_(\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_\n    raise exception\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context\n    self.dialect.do_execute(\n', '  File "/var/www/eidaws-stationlite/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute\n    cursor.execute(statement, parameters)\n', 'sqlalchemy.exc.OperationalError: (psycopg2.errors.DiskFull) could not resize shared memory segment "/PostgreSQL.541514444" to 16777216 bytes: No space left on device\nCONTEXT:  parallel worker\n\n[SQL: SELECT DISTINCT channelepoch.code AS channelepoch_code, channelepoch.locationcode AS channelepoch_locationcode, station.code AS station_code, network.code AS network_code, epoch.starttime AS epoch_starttime, epoch.endtime AS epoch_endtime, routing.starttime AS routing_starttime, routing.endtime AS routing_endtime, endpoint.url AS endpoint_url \nFROM channelepoch JOIN epoch ON channelepoch.epoch_ref = epoch.id JOIN epochtype ON epoch.epochtype_ref = epochtype.id JOIN routing ON routing.epoch_ref = epoch.id JOIN network ON channelepoch.network_ref = network.id JOIN station ON channelepoch.station_ref = station.id JOIN stationepoch ON stationepoch.station_ref = station.id JOIN endpoint ON routing.endpoint_ref = endpoint.id JOIN service ON endpoint.service_ref = service.id \nWHERE network.code LIKE %(code_1)s ESCAPE \'/\' AND station.code LIKE %(code_2)s ESCAPE \'/\' AND channelepoch.code LIKE %(code_3)s ESCAPE \'/\' AND channelepoch.locationcode LIKE %(locationcode_1)s ESCAPE \'/\' AND service.name = %(name_1)s AND epochtype.type = %(type_1)s AND stationepoch.latitude >= %(latitude_1)s AND stationepoch.latitude <= %(latitude_2)s AND stationepoch.longitude >= %(longitude_1)s AND stationepoch.longitude <= %(longitude_2)s AND (epoch.endtime > %(endtime_1)s OR epoch.endtime IS NULL) AND epoch.starttime < %(starttime_1)s]\n[parameters: {\'code_1\': \'%\', \'code_2\': \'%\', \'code_3\': \'%\', \'locationcode_1\': \'%\', \'name_1\': \'wfcatalog\', \'type_1\': \'CHANNEL\', \'latitude_1\': -90.0, \'latitude_2\': 90.0, \'longitude_1\': -180.0, \'longitude_2\': 180.0, \'endtime_1\': datetime.datetime(2020, 1, 4, 0, 0), \'starttime_1\': datetime.datetime(2020, 1, 10, 0, 0)}]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)\n']
eidaws-stationlite     | 192.168.96.3 - - [08/Sep/2021:12:28:39 +0000] "GET /eidaws/routing/1/query?service=wfcatalog&format=post&access=any&network=*&station=*&location=*&channel=*&starttime=2020-01-04T00:00:00&endtime=2020-01-10T00:00:00 HTTP/1.1" 500 400 4108845 "-" "EIDA-Federator/0.12.1"
```
